### ISSUE TITLE
TypeError when removing a component

### ISSUE THREAD

**Issue by ooflorent** [ddmills/geotic#35]
When benchmark the mutations I faced a `TypeError` when removing a component:

```
TypeError: Cannot mix BigInt and other types, use explicit conversions
    at subtractBit (file:///Users/fcailhol/Development/_lost/_noctjs/ecs-benchmark/node_modules/geotic/build/index.js:509:21)
    at removeComponent (file:///Users/fcailhol/Development/_lost/_noctjs/ecs-benchmark/node_modules/geotic/build/index.js:555:19)
    at Entity.remove (file:///Users/fcailhol/Development/_lost/_noctjs/ecs-benchmark/node_modules/geotic/build/index.js:654:7)
```

Reproduction:

```js
import { Component, Engine } from "geotic";

class Position extends Component {
  static properties = {
    x: 0,
    y: 0,
  };
}

class Velocity extends Component {
  static properties = {
    dx: 0,
    dy: 0,
  };
}

class Animation extends Component {
  static properties = {
    frame: 0,
    size: 1,
  };
}

function setup() {
  const engine = new Engine();

  engine.registerComponent(Position);
  engine.registerComponent(Velocity);
  engine.registerComponent(Animation);

  return engine.createWorld();
}

export function bench_mutate(count) {
  let world = setup();

  for (let i = 0; i < count; i++) {
    let e1 = world.createEntity();
    let e2 = world.createEntity();
    e1.add(Position);
    e1.add(Animation);
    e2.add(Position);
    e2.add(Velocity);
  }

  let all = world.createQuery({
    all: [Position],
  });

  let anims = world.createQuery({
    all: [Animation],
  });

  let vels = world.createQuery({
    all: [Velocity],
  });

  return () => {
    for (let entity of all.get()) {
      if (entity.has(Animation)) {
        entity.remove(Animation);
        entity.add(Velocity);
      } else if (entity.has(Velocity)) {
        entity.remove(Velocity);
        entity.add(Animation);
      }
    }

    for (let entity of anims.get()) {
      if (!entity) throw new Error();
    }

    for (let entity of vels.get()) {
      if (!entity) throw new Error();
    }
  };
}
```

**Comment by ddmills** [comment]
current you cannot remove component by type, you have to specify the component instance:

```js
entity.remove(entity.animation);
entity.remove(entity.velocity);
```

**Comment by ddmills** [comment]
#36
